apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        volumeMounts:
          - name: pihole-config-volume
            mountPath: /etc/pihole
          - name: pihole-dnsmasq-volume
            mountPath: /etc/dsnmasq.d
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67 # DCHP
          protocol: UDP
        - containerPort: 80
        env:
        - name: TZ
          value: 'Europe/Zurich'
        - name: DNSMASQ_USER
          value: root # CAP_SETFCAP -> Unable to set capabilities for pihole-FTL. Cannot run as non-root.
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secrets
              key: webpassword
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        livenessProbe:
            httpGet:
              path: /index.html # TODO: use proper access page?
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
      volumes:
      - name: pihole-config-volume
        persistentVolumeClaim:
          claimName: pihole-config-pvc
      - name: pihole-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - port: 80
    targetPort: 80
